# Generated by Django 4.2.7 on 2023-11-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPUServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='IP地址')),
                ('hostname', models.CharField(blank=True, max_length=50, null=True, verbose_name='主机名')),
                ('port', models.PositiveIntegerField(default=22, verbose_name='端口')),
                ('valid', models.BooleanField(default=True, verbose_name='是否可用')),
                ('can_use', models.BooleanField(default=True, verbose_name='是否可调度')),
            ],
            options={
                'verbose_name': 'GPU服务器',
                'verbose_name_plural': 'GPU服务器',
                'ordering': ('ip',),
                'unique_together': {('ip', 'port')},
            },
        ),
        migrations.CreateModel(
            name='GPUInfo',
            fields=[
                ('uuid', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='UUID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='序号')),
                ('name', models.CharField(max_length=40, verbose_name='名称')),
                ('utilization', models.PositiveSmallIntegerField(verbose_name='利用率')),
                ('memory_total', models.PositiveIntegerField(verbose_name='总显存')),
                ('memory_used', models.PositiveIntegerField(verbose_name='已用显存')),
                ('processes', models.TextField(verbose_name='进程')),
                ('use_by_self', models.BooleanField(default=False, verbose_name='是否被gputasker进程占用')),
                ('complete_free', models.BooleanField(default=False, verbose_name='完全空闲')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpus', to='gpu_info.gpuserver', verbose_name='服务器')),
            ],
            options={
                'verbose_name': 'GPU信息',
                'verbose_name_plural': 'GPU信息',
                'ordering': ('server', 'index'),
            },
        ),
    ]
