# Generated by Django 4.2.18 on 2025-12-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpuserver',
            name='last_report_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近上报时间'),
        ),
        migrations.AddField(
            model_name='gpuserver',
            name='report_token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='上报Token'),
        ),
    ]
