# Generated by Django 4.2.18 on 2025-12-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu_info', '0002_gpuserver_last_report_at_gpuserver_report_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpuinfo',
            name='busy_by_log_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='占用运行记录ID'),
        ),
    ]
