# Generated by Django 4.2.7 on 2023-11-12 16:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gpu_info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPUTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('workspace', models.CharField(max_length=200, verbose_name='工作目录')),
                ('cmd', models.TextField(verbose_name='命令')),
                ('gpu_requirement', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(0)], verbose_name='GPU数量需求')),
                ('exclusive_gpu', models.BooleanField(default=False, verbose_name='独占显卡')),
                ('memory_requirement', models.PositiveSmallIntegerField(default=0, verbose_name='显存需求(MB)')),
                ('utilization_requirement', models.PositiveSmallIntegerField(default=0, verbose_name='利用率需求(%)')),
                ('priority', models.SmallIntegerField(default=0, verbose_name='优先级')),
                ('status', models.SmallIntegerField(choices=[(-2, '未就绪'), (-1, '运行失败'), (0, '准备就绪'), (1, '运行中'), (2, '已完成')], default=0, verbose_name='状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assign_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpu_info.gpuserver', verbose_name='指定服务器')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'GPU任务',
                'verbose_name_plural': 'GPU任务',
            },
        ),
        migrations.CreateModel(
            name='GPUTaskRunningLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='序号')),
                ('pid', models.IntegerField(verbose_name='PID')),
                ('gpus', models.CharField(max_length=20, verbose_name='GPU')),
                ('log_file_path', models.FilePathField(match='.*\\.log$', path='running_log', verbose_name='日志文件')),
                ('status', models.SmallIntegerField(choices=[(-1, '运行失败'), (1, '运行中'), (2, '已完成')], default=1, verbose_name='状态')),
                ('start_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_logs', to='gpu_info.gpuserver', verbose_name='服务器')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='task.gputask', verbose_name='任务')),
            ],
            options={
                'verbose_name': 'GPU任务运行记录',
                'verbose_name_plural': 'GPU任务运行记录',
                'ordering': ('-id',),
            },
        ),
    ]
