# Generated by Django 4.2.18 on 2025-12-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gputaskrunninglog',
            name='remote_pgid',
            field=models.IntegerField(blank=True, null=True, verbose_name='远端PGID'),
        ),
        migrations.AddField(
            model_name='gputaskrunninglog',
            name='remote_pid',
            field=models.IntegerField(blank=True, null=True, verbose_name='远端PID'),
        ),
        migrations.AlterField(
            model_name='gputask',
            name='status',
            field=models.SmallIntegerField(choices=[(-2, '未就绪'), (-1, '运行失败'), (-3, '调度中'), (0, '准备就绪'), (1, '运行中'), (2, '已完成')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='gputaskrunninglog',
            name='pid',
            field=models.IntegerField(verbose_name='SSH PID'),
        ),
    ]
