# Generated by GPT-5.2 (Preview) on 2025-12-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_gputaskrunninglog_remote_pgid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gputaskrunninglog',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近心跳时间'),
        ),
        migrations.AlterField(
            model_name='gputask',
            name='status',
            field=models.SmallIntegerField(
                choices=[
                    (-2, '未就绪'),
                    (-1, '运行失败'),
                    (-4, '节点失联'),
                    (-3, '调度中'),
                    (0, '准备就绪'),
                    (1, '运行中'),
                    (2, '已完成'),
                ],
                default=0,
                verbose_name='状态',
            ),
        ),
        migrations.AlterField(
            model_name='gputaskrunninglog',
            name='status',
            field=models.SmallIntegerField(
                choices=[
                    (-1, '运行失败'),
                    (-2, '节点失联'),
                    (1, '运行中'),
                    (2, '已完成'),
                ],
                default=1,
                verbose_name='状态',
            ),
        ),
    ]
