# Generated by Django 4.2.7 on 2023-11-12 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('server_username', models.CharField(max_length=100, verbose_name='服务器用户名')),
                ('server_private_key', models.TextField(verbose_name='私钥')),
                ('server_private_key_path', models.FilePathField(blank=True, null=True, path='private_key', verbose_name='私钥文件')),
            ],
            options={
                'verbose_name': '用户设置',
                'verbose_name_plural': '用户设置',
            },
        ),
    ]
